# Generated by Django 4.2.9 on 2024-03-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('priorite', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('H', 'Haute')], max_length=20)),
                ('statut', models.CharField(choices=[('EA', 'En attente'), ('DF', 'Faite'), ('EN', 'En cours'), ('AF', 'A faire')], max_length=20)),
                ('commentaire', models.TextField()),
                ('categorie', models.ForeignKey(blank='null', null='true', on_delete=django.db.models.deletion.CASCADE, to='Taches.categorie')),
            ],
        ),
    ]
