# Generated by Django 4.2.9 on 2024-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='heure_debut',
            field=models.TimeField(blank='null', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='tache',
            name='heure_fin',
            field=models.TimeField(blank='null', null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='tache',
            name='date',
            field=models.DateField(blank='null', null='true'),
        ),
    ]
