# Generated by Django 4.2.9 on 2024-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0002_tache_heure_debut_tache_heure_fin_alter_tache_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('Ffaible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('faite', 'Faite'), ('en cours', 'En cours'), ('à faire', 'A faire')], max_length=20),
        ),
    ]
