# Generated by Django 4.2.9 on 2024-03-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Taches', '0003_alter_tache_priorite_alter_tache_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='responsable',
            field=models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='true',
        ),
    ]
