# Generated by Django 4.2.9 on 2024-03-14 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Taches', '0004_tache_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='categorie',
            field=models.ForeignKey(blank='True', null='true', on_delete=django.db.models.deletion.CASCADE, to='Taches.categorie'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date',
            field=models.DateField(blank='True', null='true'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='heure_debut',
            field=models.TimeField(blank='True', null='true'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='heure_fin',
            field=models.TimeField(blank='True', null='true'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='responsable',
            field=models.ForeignKey(blank='True', null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
